services:
  app:
    image: learn-sphere
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
      - next_cache:/app/.next
    ports:
      - "3000:3000"

volumes:
  node_modules:
  next_cache:
